"""Strudel emitter — export ScoreIR to Strudel live-coding format.

Generates JavaScript/Strudel code that can be pasted into the
Strudel REPL (strudel.cc) for browser-based instant audition.

Belongs to Layer 5 (Rendering).
"""

from __future__ import annotations

from pathlib import Path

from yao.ir.notation import midi_to_note_name
from yao.ir.score_ir import ScoreIR


def emit_strudel(score: ScoreIR, output_path: Path | None = None) -> str:
    """Convert ScoreIR to Strudel live-coding notation.

    Args:
        score: The ScoreIR to convert.
        output_path: Optional path to write the .js file.

    Returns:
        Strudel code as a string.
    """
    lines: list[str] = []
    lines.append(f"// {score.title} — generated by YaO")
    lines.append(f"// Key: {score.key}, Tempo: {score.tempo_bpm} BPM")
    lines.append("")

    for instrument in score.instruments():
        notes = score.part_for_instrument(instrument)
        if not notes:
            continue

        # Convert to Strudel note names
        strudel_notes: list[str] = []
        for note in notes[:32]:  # Limit for readability
            name = midi_to_note_name(note.pitch).lower().replace("#", "s")
            strudel_notes.append(name)

        pattern = " ".join(strudel_notes)
        lines.append(f"// {instrument}")
        lines.append(f'note("{pattern}")')
        lines.append('  .s("piano")')
        lines.append(f"  .cpm({score.tempo_bpm / 4})")
        lines.append("")

    code = "\n".join(lines)

    if output_path is not None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(code, encoding="utf-8")

    return code
